name: Deploy
on:
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::858777967843:role/github-actions-admin
          aws-region: us-east-1
      - run: yarn install --frozen-lockfile
      - name: Deploy Infra
        run: yarn deploy
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      - name: Fetch DatabaseSecretId
        run: echo "DATABASE_SECRET=$(terraform -chdir=./packages/infrastructure/cdktf.out/stacks/stablio-data output -raw DatabaseSecretId)" >> $GITHUB_ENV
      - name: Run DB migrations
        run: yarn db-migrate
